In [9]:
# pandas => 데이터를 조작하고 분석하기 위한 파이썬 라이브러리, 대규모의 데이터를 처리할 때 편리하게 사용할 수 있다. 

# pandas의 기본 객체(정수 인덱스 자동으로 만들어줌)
# series(열/=> 1차원 어레이//인덱스라는 레이블 가짐), DataFrame(시리즈가 합쳐진 것/=>2차원 어레이 )

# numpy => 수학, 과학 연산을 위한 패키지
# 숫자 그대로 입력은 불가함 ex) np.array(1,2,3,4)
# np. array([1,2,3,4]) 가능
# np. array((1,2,3,4)) 가능 
# // 직접 입력만 하는 건 불가능

In [31]:
# 정수형 series 만들기
import pandas as pd #as 뒤에는 별칭
s=pd.Series([1,2,3,4,8])
print(s)
# dtype = 들어있는 자료형 알려줌


0    1
1    2
2    3
3    4
4    8
dtype: int64


In [32]:
# 실수형 series(float는 실수)
s = pd.Series([1.3,2.5,3.6,2.3,1.2])
print(s)

0    1.3
1    2.5
2    3.6
3    2.3
4    1.2
dtype: float64


In [33]:
# 실수형, 정수형 series (섞임)
s = pd.Series([1,2.3,5,6])
print(s)

0    1.0
1    2.3
2    5.0
3    6.0
dtype: float64


In [13]:
# 인덱스 지정하기
s = pd.Series([1,2.3,5,6], index =['a', 'b', 'c', 'd'])
print(s)

a    1.0
b    2.3
c    5.0
d    6.0
dtype: float64


In [21]:
# 넘파이로 어레이 만들기
import numpy as np
a= np.array([1,2,3])
print(a)
b = np.zeros(5)
print(b)
c = np.ones((2,3))
print(c)

[1 2 3]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
# array 끼리 더하기 (요소끼리 더하기)
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
print(np.add(a,b))

# 요소별 곱하기
print(np.multiply(a,b))

# 요소별 평균 구하기 np.mean((어레이집어넣기))
print(np.mean(a))
print(np.mean(b))

[5 5 5 5]
[4 6 6 4]
2.5
2.5


In [43]:
# 0과 1 사이에서 균일한 분포를 갖는 숫자 샘플링
a = np.random.rand(2,5)
print(a)

# 표준 정규 분포를 갖는 숫자들 샘플링
b = np.random.randn(2,4)
print(b)

[[0.72032905 0.7693116  0.10070278 0.20713535 0.38653764]
 [0.00715344 0.87065797 0.04759461 0.73585183 0.10090741]]
[[ 0.26669838  1.9491668   0.20310489 -0.36035879]
 [ 0.89067186 -0.08696761  1.35302785 -0.1314746 ]]


In [47]:
# 파이 값
a = np.pi
print(a)

# 오일러 상수
b = np.e
print(b)

3.141592653589793
2.718281828459045


In [50]:
# 넘파이 어레이 만들기
a = np.array([1.2,5,6,8])
print(type(a))
print(a)
# 어레이 요소의 자료형을 알고싶을때
print(a.dtype)

<class 'numpy.ndarray'>
[1.2 5.  6.  8. ]
float64


In [57]:
# 여러 개의 어레이 만들기
a = np.array([(1,2,3,4), (1,2,3,4)])
print(a)


[[1 2 3 4]
 [1 2 3 4]]


In [60]:
# 타입 지정
a = np.array([[1,2,3], [4,5,6]], dtype=complex)
print(a)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
