In [9]:
# pandas => 데이터를 조작하고 분석하기 위한 파이썬 라이브러리, 대규모의 데이터를 처리할 때 편리하게 사용할 수 있다. 

# pandas의 기본 객체(정수 인덱스 자동으로 만들어줌)
# series(열/=> 1차원 어레이//인덱스라는 레이블 가짐), DataFrame(시리즈가 합쳐진 것/=>2차원 어레이 )

# numpy => 수학, 과학 연산을 위한 패키지
# 숫자 그대로 입력은 불가함 ex) np.array(1,2,3,4)
# np. array([1,2,3,4]) 가능
# np. array((1,2,3,4)) 가능 
# // 직접 입력만 하는 건 불가능

In [31]:
# 정수형 series 만들기
import pandas as pd #as 뒤에는 별칭
s=pd.Series([1,2,3,4,8])
print(s)
# dtype = 들어있는 자료형 알려줌


0    1
1    2
2    3
3    4
4    8
dtype: int64


In [32]:
# 실수형 series(float는 실수)
s = pd.Series([1.3,2.5,3.6,2.3,1.2])
print(s)

0    1.3
1    2.5
2    3.6
3    2.3
4    1.2
dtype: float64


In [33]:
# 실수형, 정수형 series (섞임)
s = pd.Series([1,2.3,5,6])
print(s)

0    1.0
1    2.3
2    5.0
3    6.0
dtype: float64


In [13]:
# 인덱스 지정하기
s = pd.Series([1,2.3,5,6], index =['a', 'b', 'c', 'd'])
print(s)

a    1.0
b    2.3
c    5.0
d    6.0
dtype: float64


In [21]:
# 넘파이로 어레이 만들기
import numpy as np
a= np.array([1,2,3])
print(a)
b = np.zeros(5)
print(b)
c = np.ones((2,3))
print(c)

[1 2 3]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
# array 끼리 더하기 (요소끼리 더하기)
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
print(np.add(a,b))

# 요소별 곱하기
print(np.multiply(a,b))

# 요소별 평균 구하기 np.mean((어레이집어넣기))
print(np.mean(a))
print(np.mean(b))

[5 5 5 5]
[4 6 6 4]
2.5
2.5


In [43]:
# 0과 1 사이에서 균일한 분포를 갖는 숫자 샘플링
a = np.random.rand(2,5)
print(a)

# 표준 정규 분포를 갖는 숫자들 샘플링
b = np.random.randn(2,4)
print(b)

[[0.72032905 0.7693116  0.10070278 0.20713535 0.38653764]
 [0.00715344 0.87065797 0.04759461 0.73585183 0.10090741]]
[[ 0.26669838  1.9491668   0.20310489 -0.36035879]
 [ 0.89067186 -0.08696761  1.35302785 -0.1314746 ]]


In [47]:
# 파이 값
a = np.pi
print(a)

# 오일러 상수
b = np.e
print(b)

3.141592653589793
2.718281828459045


In [50]:
# 넘파이 어레이 만들기
a = np.array([1.2,5,6,8])
print(type(a))
print(a)
# 어레이 요소의 자료형을 알고싶을때
print(a.dtype)

<class 'numpy.ndarray'>
[1.2 5.  6.  8. ]
float64


In [57]:
# 여러 개의 어레이 만들기
a = np.array([(1,2,3,4), (1,2,3,4)])
print(a)


[[1 2 3 4]
 [1 2 3 4]]


In [60]:
# 타입 지정
a = np.array([[1,2,3], [4,5,6]], dtype=complex)
print(a)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [67]:
no = [1,2,3]
subj = ["수학", "과학", "파이썬"]
subject = pd.DataFrame()
subject['과목번호']= no
subject['과목명'] = subj
print(subject)
subject.to_excel('C:\Wujin_py\subject.xlsx', index=False)

   과목번호  과목명
0     1   수학
1     2   과학
2     3  파이썬


In [68]:
# xlsx 엑셀
# csv 엑셀이랑 똑같은데  , 기준으로 갈라짐
subject.to_csv('C:\Wujin_py\subject.csv', encoding='utf-8-sig', index = True)

In [86]:
# 데이터 프레임은 파이썬의 리스트와 딕셔너리의 조합이다. 
df = pd.DataFrame({"이름" : ["홍길동", "홍길순", "임꺽정"], "나이" : [20, 50, 32], "성별" : ["남자", "여자", "남자" ]})
print(df)
print("========# // 데이터 프레임에서 성별컬럼만 출력==========")
print(df["이름"])
print("==================")
print(df["성별"])
# 데이터 프레임에 고향컬럼 추가
home = pd.Series(["서울", "부산", "대전"], name = "고향")
df["고향"] = home
print(df)
# 집계함수
# 평균, 최댓값, 최솟값
print("===나이 평균값===")
print(df["나이"].mean())
print("===나이 최댓값===")
print(df["나이"].max())
print("===나이 최솟값===")
print(df["나이"].min())

    이름  나이  성별
0  홍길동  20  남자
1  홍길순  50  여자
2  임꺽정  32  남자
========# // 데이터 프레임에서 성별컬럼만 출력==========
0    홍길동
1    홍길순
2    임꺽정
Name: 이름, dtype: object
0    남자
1    여자
2    남자
Name: 성별, dtype: object
    이름  나이  성별  고향
0  홍길동  20  남자  서울
1  홍길순  50  여자  부산
2  임꺽정  32  남자  대전
===나이 평균값===
34.0
===나이 최댓값===
50
===나이 최솟값===
20


In [90]:
df = pd.DataFrame({"이름" : ["홍길동", "홍길순", "임꺽정"], "나이" : [20, 50, 32], "성별" : ["남자", "여자", "남자" ]})
# 통계 (전체적인 기본 통계 출력)
print(df.describe())
# head는 위에서부터 원하는 것 까지 잘라서 가져오기
print(df.head(2))
# tail은 밑에서부터 원하는 것 까지 잘라서 가져오기
print(df.tail(2))


              나이
count   3.000000
mean   34.000000
std    15.099669
min    20.000000
25%    26.000000
50%    32.000000
75%    41.000000
max    50.000000
    이름  나이  성별
0  홍길동  20  남자
1  홍길순  50  여자
    이름  나이  성별
1  홍길순  50  여자
2  임꺽정  32  남자


In [116]:
# 엑셀 불러오기
df = pd.read_excel('order.xlsx')
print(df)
print("========================")
print("1. 손흥민이 몇 번 주문했나?")
# => count()
is_son = df["name"] == "손흥민"
print(df[is_son]["order_no"].count())
print("========================")

print("2. 손흥민이 산 상품은?")
is_son = df["name"] == "손흥민"
print(df[is_son]["product"])

print("========================")
print("3. 스커트를 산 사람은?")
buy = df["product"] =="스커트"
print(df[buy]["name"])

print("========================")
print("4. 가장 많이 주문한 사람의 아이디와 이름, 주문 횟수는?")
newdf = df.groupby(["user_id", "name"])["order_no"].count().reset_index(name = "count")
# 기본 정렬 방식은 오름차순, 내림차순으로 정렬하고 싶을 경우 ascending = False
newdf = newdf.sort_values("count", ascending=False)
print(newdf)
# => count(), groupby(), sort_values()

print("========================")
print("5. 김지원이 사용한 총 금액은?")
jw = df["name"] =="김지원"
print(df[jw]["price"].sum())


# sum()

   Unnamed: 0  order_no user_id user_pass name address product    price  brand
0           0         1   user1     pass1  손흥민      런던     운동화   100000    나이키
1           1         2   user2     pass2   설현      서울      코트   150000    버버리
2           2         3   user3     pass3   원빈      대전     반바지    30000   유니클로
3           3         4   user4     pass4  송혜교      대구     스커트    55000     자라
4           4         5   user5     pass5  소지섭      부산      코트  1100000   알레그리
5           5         6   user6     pass6  김지원      울산     티셔츠     9900   지오다노
6           6         7   user6     pass6  김지원      울산     운동화   220000     텐디
7           7         8   user1     pass1  손흥민      런던     스커트    30000  크로커다일
8           8         9   user1     pass1  손흥민      런던      코트   580000    띠어리
1. 손흥민이 몇 번 주문했나?
3
2. 손흥민이 산 상품은?
0    운동화
7    스커트
8     코트
Name: product, dtype: object
3. 스커트를 산 사람은?
3    송혜교
7    손흥민
Name: name, dtype: object
4. 가장 많이 주문한 사람의 아이디와 이름, 주문 횟수는?
  user_id name  count
0   