In [9]:
# pandas => 데이터를 조작하고 분석하기 위한 파이썬 라이브러리, 대규모의 데이터를 처리할 때 편리하게 사용할 수 있다. 

# pandas의 기본 객체(정수 인덱스 자동으로 만들어줌)
# series(열/=> 1차원 어레이//인덱스라는 레이블 가짐), DataFrame(시리즈가 합쳐진 것/=>2차원 어레이 )

In [31]:
# 정수형 series 만들기
import pandas as pd #as 뒤에는 별칭
s=pd.Series([1,2,3,4,8])
print(s)
# dtype = 들어있는 자료형 알려줌


0    1
1    2
2    3
3    4
4    8
dtype: int64


In [32]:
# 실수형 series(float는 실수)
s = pd.Series([1.3,2.5,3.6,2.3,1.2])
print(s)

0    1.3
1    2.5
2    3.6
3    2.3
4    1.2
dtype: float64


In [33]:
# 실수형, 정수형 series (섞임)
s = pd.Series([1,2.3,5,6])
print(s)

0    1.0
1    2.3
2    5.0
3    6.0
dtype: float64


In [13]:
# 인덱스 지정하기
s = pd.Series([1,2.3,5,6], index =['a', 'b', 'c', 'd'])
print(s)

a    1.0
b    2.3
c    5.0
d    6.0
dtype: float64


In [21]:
# 넘파이로 어레이 만들기
import numpy as np
a= np.array([1,2,3])
print(a)
b = np.zeros(5)
print(b)
c = np.ones((2,3))
print(c)

[1 2 3]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [30]:
# array 끼리 더하기 (요소끼리 더하기)
a = np.array([1,2,3,4])
b = np.array([4,3,2,1])
print(np.add(a,b))

# 요소별 곱하기
print(np.multiply(a,b))

# 요소별 평균구하기 np.mean((어레이집어넣기))
print(np.mean(a))
print(np.mean(b))

[5 5 5 5]
[4 6 6 4]
2.5
2.5
